// Agent Studio DOM registry kept separate from the legacy Author workspace surface.

var AgentStudioDOM = (() => ({
  shell: DOMShared.query("#agent-studio-shell"),
  start: DOMShared.query("#agent-studio-start"),
  workbench: DOMShared.query("#agent-studio-workbench"),
  title: DOMShared.query("#agent-studio-title"),
  genre: DOMShared.query("#agent-studio-genre"),
  length: DOMShared.query("#agent-studio-length"),
  readerGoal: DOMShared.query("#agent-studio-reader-goal"),
  remix: DOMShared.query("#agent-studio-remix"),
  cover: DOMShared.query("#agent-studio-cover"),
  startButton: DOMShared.query("#agent-studio-start-button"),
  advancedButton: DOMShared.query("#agent-studio-advanced-button"),
  workTitle: DOMShared.query("#agent-studio-work-title"),
  workMeta: DOMShared.query("#agent-studio-work-meta"),
  chapters: DOMShared.query("#agent-studio-chapters"),
  branches: DOMShared.query("#agent-studio-branches"),
  exportButton: DOMShared.query("#agent-studio-export"),
  validateButton: DOMShared.query("#agent-studio-validate"),
  previewButton: DOMShared.query("#agent-studio-preview"),
  readerTitle: DOMShared.query("#agent-studio-reader-title"),
  readerBody: DOMShared.query("#agent-studio-reader-body"),
  readerProgress: DOMShared.query("#agent-studio-reader-progress"),
  readerFeedback: DOMShared.query("#agent-studio-reader-feedback"),
  chapterPrev: DOMShared.query("#agent-studio-chapter-prev"),
  chapterNext: DOMShared.query("#agent-studio-chapter-next"),
  choiceCards: DOMShared.query("#agent-studio-choice-cards"),
  generationStatus: DOMShared.query("#agent-studio-generation-status"),
  directorIntent: DOMShared.query("#agent-studio-director-intent"),
  quickButtons: DOMShared.queryAll("[data-agent-studio-intent]"),
  generateButton: DOMShared.query("#agent-studio-generate"),
  branchButton: DOMShared.query("#agent-studio-create-branch"),
  quality: DOMShared.query("#agent-studio-quality"),
  branchRouteSelect: DOMShared.query("#agent-studio-route-select"),
}))();
