// Shell-scoped DOM registry.

var ShellDOM = (() => ({
  appShell: DOMShared.query("#app-shell"),
  shellStatusBanner: DOMShared.query("#shell-status-banner"),
  shellLiveRegion: DOMShared.query("#shell-live-region"),
  shellToastStack: DOMShared.query("#shell-toast-stack"),
  shellAuthStage: DOMShared.query("#shell-auth-stage"),
  shellAuthHeadline: DOMShared.query("#shell-auth-headline"),
  shellAuthCopy: DOMShared.query("#shell-auth-copy"),
  shellAuthRoleButtons: DOMShared.queryAll("[data-shell-register-role]"),
  shellAuthActorId: DOMShared.query("#shell-auth-actor-id"),
  shellAuthDisplayName: DOMShared.query("#shell-auth-display-name"),
  shellAuthPassword: DOMShared.query("#shell-auth-password"),
  shellAuthRegister: DOMShared.query("#shell-auth-register"),
  shellAuthLogin: DOMShared.query("#shell-auth-login"),
  shellAuthLogout: DOMShared.query("#shell-auth-logout"),
  shellAuthRoleSummary: DOMShared.query("#shell-auth-role-summary"),
  shellAuthStatus: DOMShared.query("#shell-auth-status"),
  authRouteStage: DOMShared.query("#auth-route-stage"),
  authRouteContent: DOMShared.query("#auth-route-content"),
  shellSessionSummary: DOMShared.query("#shell-session-summary"),
  shellSessionCopy: DOMShared.query("#shell-session-copy"),
  shellSessionLogout: DOMShared.query("#shell-session-logout"),
  shellDebugToggle: DOMShared.query("#shell-debug-toggle"),
  shellProductStatus: DOMShared.query("#shell-product-status"),
  shellContextCopy: DOMShared.query("#shell-context-copy"),
  shellReaderId: DOMShared.query("#shell-reader-id"),
  productSubnav: DOMShared.query("#product-subnav"),
  productSubnavLabel: DOMShared.query("#product-subnav-label"),
  productSubnavDescription: DOMShared.query("#product-subnav-description"),
  productSubnavActions: DOMShared.query("#product-subnav-actions"),
  modeReader: DOMShared.query("#mode-reader"),
  modeAuthor: DOMShared.query("#mode-author"),
  modeCustomer: DOMShared.query("#mode-customer"),
  modeOps: DOMShared.query("#mode-ops"),
  readerShellV2: DOMShared.query("#reader-shell-v2"),
  readerShell: DOMShared.query("#reader-shell"),
  authorShell: DOMShared.query("#author-shell"),
  customerShell: DOMShared.query("#customer-shell"),
  opsShell: DOMShared.query("#ops-shell"),
  apiStatus: DOMShared.query("#api-status"),
}))();
