// Bootstrap exposure layer extracted from app.js so classic scripts consume a focused assembly surface.

var {
  hydrateShellRoute,
  syncShellRoute,
} = RouteSyncRuntime;

var {
  setReaderWorkspace,
  setAuthorWorkspace,
  setOpsWorkspace,
  installScrollWorkspaceBridge,
} = WorkspaceLayoutRuntime;

var {
  syncViewMode,
  syncProductMode,
  updateStatus,
  toggleDebugMode,
} = ShellStatusRuntime;

var {
  authorStageLabel,
  focusAuthorPanel,
  prefillAuthorCommentAnchor,
  jumpToAuthorChapter,
  activeAuthorReviewerId,
  activeAuthorActorId,
  activeAuthorActorRole,
  currentAuthorInboxFilters,
  authorCollaborationHeaders,
  selectAuthorThread,
  mergeAuthorReviewerInbox,
  syncAuthorNotificationPreferenceInputs,
  persistAuthorAuthSession,
  restoreAuthorAuthSession,
  renderAuthorAuthStatus,
  refreshAuthorReviewerInbox,
  updateAuthorThreadStatusInline,
  updateAuthorNotificationStatus,
  bulkUpdateAuthorNotificationStatus,
  decideAuthorApprovalForWorld,
  addAuthorThreadWatcher,
  removeAuthorThreadWatcher,
  replyToSelectedAuthorThread,
  addAuthorDraftWatcher,
  removeAuthorDraftWatcher,
  refreshAuthorNotificationPreferences,
  saveAuthorNotificationPreference,
  registerAuthorAuthIdentity,
  loginAuthorAuthIdentity,
  hydrateAuthorAuthSession,
  logoutAuthorAuthIdentity,
  validateDraftVersion,
  simulateDraftVersion,
  submitDraftVersion,
  createAuthorCommentThread,
  requestAuthorApproval,
  decideAuthorApproval,
  runAuthorWorkflowAction,
  populateAuthorBriefForm,
  applyAuthorPresetDefaults,
  buildAuthorBriefPayload,
  getActiveDraftCharacters,
  getActiveDraftScenes,
  getActiveSeriesPlan,
  getActiveVolumePlans,
  getActiveArcPlans,
  applyDraftWorldpackMutation,
  resequenceArcOrders,
  reorderArcWithinVolume,
  reorderTaskWithinArc,
  moveTaskAcrossArcs,
  selectedCharacterIndex,
  selectedSceneIndex,
  renderAuthorDraftDetail,
  renderCharacterEditor,
  renderSceneEditor,
  renderLongformWorkbench,
  renderPromiseLedgerWorkbench,
  renderSeriesVolumeArcPromiseMapping,
  renderChapterTaskSimulationLinking,
  renderRewritePatchPreview,
  renderSimulationDiffCheckpoint,
  exportRewritePatchPreview,
  runCheckpointAwareResimulate,
  splitSelectedTaskPromiseTargets,
  mergeObservedPromisesIntoTargets,
  applySelectedTaskRewritePrefill,
  bulkApplyTaskToSimulation,
  renderContinuityDiffWorkbench,
  parseMultilineList,
  splitPromiseTargetList,
  normalizeLongformArcTasks,
  formatMultilineList,
  parseLabelMap,
  formatLabelMap,
  parseSceneHooks,
  formatSceneHooks,
  renderStylePacingHookControls,
  applyStylePacingHookControls,
  buildSimulationDiffSummary,
  renderAuthorRevisionPanels,
  renderAuthorDrafts,
  renderAuthorWorkflow,
  renderAuthorReports,
  renderAuthorCompare,
  renderAuthorCollaboration,
  refreshAuthorSurface,
  bindAuthorWorkspaceEvents,
  initializeAuthorWorkspaceRuntime,
  createDraftFromCurrentWorld,
  createDraftFromBrief,
  saveCapabilityAssets,
  saveCharacterCard,
  saveSceneBlueprint,
  bootstrapLongformWorkbench,
  saveLongformWorkbench,
  savePromiseStateWorkbench,
  saveContinuityOverrideWorkbench,
  jumpToSelectedCompareChapter,
  commentSelectedContinuityChapter,
  jumpToSelectedPromiseChapter,
  commentSelectedPromise
} = AuthorWorkspaceRuntime;

var {
  refreshCustomerSurface,
  initializeCustomerWorkspaceRuntime,
} = CustomerWorkspaceRuntime;

var {
  initializeAgentStudioRuntime,
} = AgentStudioRuntime;

var {
  reviewStatusLabel,
  summarizeChecklistEvidence,
  applySupportPrefill,
  applyGovernanceCasePrefill,
  openLearnedWorldDetail,
  openLearnedIssueDetail,
  selectReviewBacklogItem
} = OpsShared;

var {
  currentOpsNavigationContext,
  OPS_REFRESH_SCOPE_ALL,
  normalizeOpsRefreshScopes,
  syncOpsNavigationContext,
  refreshOpsReleaseWorkspace,
  refreshOpsAlerts,
  refreshOpsSurface,
  refreshOpsAccountFlow,
  refreshOpsReleaseFlow,
  refreshOpsJobsFlow,
  refreshOpsLearnedFlow
} = OpsRefreshRuntime;

var {
  renderOpsSurface
} = OpsRenderRuntime;

var {
  submitPromotionDecision,
  submitRerankerPromotionDecision,
  submitProviderRollout,
  runDataIntegrityRepair,
  submitAssistedGateConfig,
  submitAssistedRerankConfig,
  createGovernanceCase,
  updateGovernanceCaseStatus,
  applyGovernanceRestriction,
  releaseGovernanceRestriction,
  assignGovernanceCase,
  addGovernanceEvidence,
  refreshGovernanceAuditExport,
  createRuntimeBackup,
  restoreRuntimeBackup,
  runRecoveryDrill,
  requestRuntimeRestore,
  approveRuntimeRestore,
  revokeRuntimeRestore,
  executeRuntimeRestore,
  retryAsyncJob,
  resumeAsyncJob,
  recoverAsyncJobIncidents,
  enforceAsyncJobRetention,
  runColdStartRecoveryDrill,
  exportAsyncJobHandoffBundle,
  acknowledgeAsyncJob,
  shipRemoteArtifacts,
  escalateHandoffSla,
  enqueueNotificationRetry,
  processNotificationRetry,
  runLearnedTraining,
  grantOpsSubscription,
  changeOpsSubscriptionState,
  grantOpsWallet,
  debitOpsWallet,
  reconcileOpsSubscription,
  retryOpsSubscriptionPayment,
  replayOpsBillingEvent,
  updateSelectedOpsAlertStatus,
  openSelectedOpsAlertInvestigation,
  followOpsNavigationRecommendation,
  runOpsInvestigation,
  exportOpsInvestigationTrace,
  revokeOpsEntitlement
} = OpsActionsRuntime;

var {
  bindOpsEvents,
  initializeOpsRuntime,
  submitOpsReviewCapture,
  submitOpsPreferenceCapture,
  submitOpsRankingCapture
} = OpsRuntime;

var ReaderRuntimeExports =
  (typeof ReaderShellV2 === "object" && ReaderShellV2)
  || (typeof ReaderRuntime === "object" && ReaderRuntime)
  || {};

var {
  activeReaderId,
  refreshReaderEntitlements,
  startReaderCheckout,
  retryReaderSubscriptionPayment,
  renewReaderSubscription,
  cancelReaderSubscription,
  grantReaderEntitlement,
  renderIntentPrefill,
  worldDisplayMeta,
  renderWorldGallery,
  renderSessionLibrary,
  renderSuggestedInputs,
  renderRoutePreview,
  spotlightPreviewResult,
  spotlightChapter,
  setTone,
  getStorySource,
  renderStorybook,
  renderLatestStep,
  renderStoryFeed,
  renderReplay,
  updateBundleSummary,
  loadExampleBundle,
  refreshExamples,
  refreshSessionLibrary,
  bootstrapWorld,
  restoreSession,
  deleteSession,
  previewRoute,
  stepSession,
  resetOutput,
  bootstrapHealth,
  bindReaderEvents,
  initializeReaderRuntime,
} = ReaderRuntimeExports;
