// Shared state runtime extracted from app.js so product runtimes can depend on narrower state buckets.

var StateRuntime = (() => {
  const shellState = {
    activeProduct: "reader",
    authPage: null,
    debug: false,
    adminViewEnabled: false,
    adminViewBridgeToken: null,
    startupRouteProduct: null,
    startupRouteWorkspace: null,
    readerWorkspace: "landing",
    authorWorkspace: "studio",
    customerWorkspace: "overview",
    opsWorkspace: "dashboard",
    initializedGuidedWorkspaces: false,
    pendingSessionId: null,
    lastReaderView: "experience",
  };

  const readerState = {
    examples: [],
    shelfWorlds: [],
    currentBundle: null,
    worldId: null,
    worldVersionId: null,
    readerId: "reader_demo",
    readerAuthSession: null,
    readerEntitlements: [],
    readerCheckoutSession: null,
    readerSubscription: null,
    pendingCheckoutSessionId: null,
    pendingCheckoutStatus: null,
    pendingCheckoutContext: null,
    sessionPaywall: null,
    sessionId: null,
    currentState: null,
    latestStep: null,
    latestStepFailure: null,
    readerGenerationJob: null,
    continuityContract: null,
    continuityDiagnostics: {
      restore_success_count: 0,
      paywall_resume_ready_count: 0,
      post_checkout_resume_success_count: 0,
      quality_guard_context_retained_count: 0,
    },
    latestPreview: null,
    replay: null,
    sessionMedia: { coverImage: "", atmosphereImage: "" },
    intentPrefill: null,
    sessionLibrary: [],
    authoredWorkLibrary: [],
    activeAuthoredWorkPreview: null,
    activeTone: "premium_prose",
    activeView: "experience",
    selectedReplayIndex: null,
    selectedIntentOverride: null,
  };

  const authorState = {
    authorDrafts: [],
    activeDraftVersionId: null,
    activeDraftDetail: null,
    authorWorks: [],
    activeWorkId: null,
    activeWorkDetail: null,
    activeWorkChapterIndex: null,
    activeWorkChapterDetail: null,
    activeWorkChapterDraft: null,
    activeWorkChapterDirty: false,
    activeWorkSaveState: "idle",
    pendingAuthorBranchSeed: null,
    authorBranchExecutionState: null,
    authorWorkDiagnostics: null,
    authorWorkQualityGateFailure: null,
    authorDraftSection: "assets",
    authorValidationReport: null,
    authorSimulationReport: null,
    authorPreviousSimulationReport: null,
    selectedAuthorRevisionIndex: null,
    selectedAuthorVolumeId: null,
    selectedAuthorArcId: null,
    selectedAuthorTaskId: null,
    draggingAuthorArcId: null,
    draggingAuthorTaskId: null,
    selectedAuthorPromiseId: null,
    selectedAuthorSimulationChapterIndex: null,
    selectedAuthorContinuityChapterIndex: null,
    authorRepairLoopHint: null,
    authorCurrentRewritePatchExport: null,
    authorBriefTemplate: null,
    authorAccessSnapshot: null,
    authorWorkflowSummary: null,
    authorCollaborationSummary: null,
    authorReviewerInbox: null,
    authorReviewerInboxNextCursor: null,
    authorReviewerInboxHasMore: false,
    authorReviewerInboxSearch: "",
    authorNotificationPreferences: null,
    authorAuthSession: null,
    selectedAuthorThreadId: null,
    authorInlineReplyDraft: "",
    authorReviewerInboxVisibleNotificationIds: [],
    agentStudio: null,
  };

  const opsState = {
    opsReviewQueue: [],
    opsReviewHub: null,
    opsSelectedReviewItemId: null,
    opsSelectedReviewItemDetail: null,
    opsSelectedReviewWorkDetail: null,
    selectedOpsReleaseBlockerKey: null,
    selectedOpsReleaseBlockerCheckKey: null,
    opsWorldStatuses: [],
    opsWorldHistories: [],
    selectedOpsWorldId: null,
    opsNavigationModel: null,
    opsNavigationPinned: false,
    opsInvestigationPinned: false,
    opsRefreshRequestId: 0,
    opsReleaseWorkspace: null,
    opsMeters: [],
    opsSchemaLifecycle: null,
    opsDataIntegrity: null,
    opsDataIntegrityRepair: null,
    opsDeploymentHealthGate: null,
    opsPreflightVerification: null,
    opsDeploymentRunbook: null,
    opsIncidentPlaybook: null,
    opsRecoveryDrillResult: null,
    opsAsyncJobSummary: null,
    opsAsyncJobBootReconcile: null,
    opsAsyncJobIncidents: null,
    opsAsyncJobArtifactRetention: null,
    opsAsyncJobOperatorHistory: null,
    opsAsyncJobHandoffBundle: null,
    opsAsyncJobRemoteShipping: null,
    opsAsyncJobHandoffSla: null,
    opsAsyncJobAdapterValidation: null,
    opsAsyncJobAdapterHealthProbe: null,
    opsAsyncJobNotificationReceipts: null,
    opsAsyncNotificationRetryQueue: null,
    opsAsyncRetryPolicies: null,
    opsAsyncNotificationDeadLetterQueue: null,
    opsAsyncRetryOutcomeDashboard: null,
    opsAsyncJobs: [],
    opsRuntimeIncidentSnapshot: null,
    opsRuntimeReceipts: [],
    opsQualitySummary: null,
    opsQualityEvents: [],
    opsSelectedQualityTraceId: null,
    opsQualityTraceDetail: null,
    opsProviderRouting: null,
    opsProviderRollout: null,
    opsProviderRuntimeMetrics: null,
    opsStoryBootstrapWorldSummary: [],
    opsStoryBootstrapWorldDetail: null,
    opsCommercializationSummary: null,
    opsProductionSignoffDetail: null,
    opsSubscriptionAudit: null,
    opsAccountDetail: null,
    opsAccountWorkspace: null,
    opsAlertsFeed: null,
    opsAlertDetail: null,
    selectedOpsAlertId: null,
    opsGovernanceSnapshot: null,
    opsGovernanceExport: null,
    opsGovernanceDetail: null,
    opsInvestigationBundle: null,
    opsEvalMetrics: null,
    opsCrossPackQuality: null,
    opsLearnedDashboard: null,
    opsLearnedImpact: null,
    opsLearnedCadence: null,
    opsLearnedAssistedGate: null,
    opsLearnedAssistedRerank: null,
    opsLearnedReviewQuality: null,
    opsLearnedTrainingResult: null,
    opsLearnedEvidence: null,
    opsLearnedCompare: null,
    opsLearnedRollout: null,
    opsLearnedDataOps: null,
    opsLearnedPromotion: null,
    opsLearnedRerankerPromotion: null,
    opsPreferenceSamples: [],
    opsRankingSamples: [],
    opsLearnedDetail: null,
    opsLastActionImpact: null,
    opsReviewCaptureTarget: null,
  };

  const customerState = {
    accountDetail: null,
    workspacePayload: null,
    selectedCampaignId: null,
  };

  return {
    shellState,
    readerState,
    authorState,
    customerState,
    opsState,
  };
})();

var shellState = StateRuntime.shellState;
var readerState = StateRuntime.readerState;
var authorState = StateRuntime.authorState;
var customerState = StateRuntime.customerState;
var opsState = StateRuntime.opsState;
